# Supported funding platforms for this project

# GitHub Sponsors (Username only)
github: huanguan1978

# Buy Me a Coffee (Username only)
buy_me_a_coffee: huanguan1978

# Custom funding links (Use for platforms like ifdian)
custom:
  - https://ifdian.net/a/huanguan1978