part of '../ft.dart';

/// Initializes the custom text MIME type resolver with predefined mappings.
void doTextMimeInit() => _textMimeMap.forEach((k, v) => doTextMimeAdd(k, v));

/// Adds a custom text MIME type mapping for a given file extension.
///
/// - [extension]: The file extension (e.g., 'txt', 'csv').
/// - [mimeType]: The corresponding MIME type (e.g., 'text/plain', 'text/csv').
void doTextMimeAdd(String extension, String mimeType) =>
    _textMimeResolver.addExtension(extension, mimeType);

/// Checks if a file is considered a text file based on its MIME type.
///
/// - [path]: The path to the file.
/// - [headerBytes]: Optional header bytes for more accurate MIME type detection.
///
/// Returns `true` if the file's MIME type is recognized as text, `false` otherwise.
///
/// ```dart
/// doTextMimeInit(); // initializes
/// print(isTextMimeType('a.txt')); // true
/// print(isTextMimeType('a.pdf')); // false
/// print(isTextMimeType('a.yml')); // false
/// // add a custom text mimetype， yml|yaml is a config language.
/// doTextMimeAdd('yml', 'text/yaml');
/// print(isTextMimeType('a.yml')); // true
/// ```
bool isTextMimeType(String path, {List<int>? headerBytes}) {
  final mime = _textMimeResolver.lookup(path, headerBytes: headerBytes) ?? '';
  return mime.isNotEmpty;
}

final MimeTypeResolver _textMimeResolver = MimeTypeResolver.empty();
final Map<String, String> _textMimeMap = <String, String>{
  // val.startwith('text/') from 'package:mime/src/default_extension_map.dart';
  '3dml': 'text/vnd.in3d.3dml',
  'appcache': 'text/cache-manifest',
  'asm': 'text/x-asm',
  'c': 'text/x-c',
  'cc': 'text/x-c',
  'conf': 'text/plain',
  'cpp': 'text/x-c',
  'css': 'text/css',
  'csv': 'text/csv',
  'curl': 'text/vnd.curl',
  'cxx': 'text/x-c',
  'dart': 'text/x-dart',
  'dcurl': 'text/vnd.curl.dcurl',
  'def': 'text/plain',
  'dic': 'text/x-c',
  'dsc': 'text/prs.lines.tag',
  'etx': 'text/x-setext',
  'f': 'text/x-fortran',
  'f77': 'text/x-fortran',
  'f90': 'text/x-fortran',
  'flx': 'text/vnd.fmi.flexstor',
  'fly': 'text/vnd.fly',
  'for': 'text/x-fortran',
  'gv': 'text/vnd.graphviz',
  'h': 'text/x-c',
  'hh': 'text/x-c',
  'htm': 'text/html',
  'html': 'text/html',
  'ics': 'text/calendar',
  'ifb': 'text/calendar',
  'in': 'text/plain',
  'jad': 'text/vnd.sun.j2me.app-descriptor',
  'java': 'text/x-java-source',
  'js': 'text/javascript',
  'list': 'text/plain',
  'log': 'text/plain',
  'man': 'text/troff',
  'mcurl': 'text/vnd.curl.mcurl',
  'md': 'text/markdown',
  'markdown': 'text/markdown',
  'me': 'text/troff',
  'mjs': 'text/javascript',
  'ms': 'text/troff',
  'n3': 'text/n3',
  'nfo': 'text/x-nfo',
  'opml': 'text/x-opml',
  'p': 'text/x-pascal',
  'pas': 'text/x-pascal',
  'roff': 'text/troff',
  'rtx': 'text/richtext',
  's': 'text/x-asm',
  'scurl': 'text/vnd.curl.scurl',
  'sfv': 'text/x-sfv',
  'sgm': 'text/sgml',
  'sgml': 'text/sgml',
  'spot': 'text/vnd.in3d.spot',
  'sub': 'text/vnd.dvb.subtitle',
  't': 'text/troff',
  'text': 'text/plain',
  'tr': 'text/troff',
  'tsv': 'text/tab-separated-values',
  'ttl': 'text/turtle',
  'txt': 'text/plain',
  'uri': 'text/uri-list',
  'uris': 'text/uri-list',
  'urls': 'text/uri-list',
  'uu': 'text/x-uuencode',
  'vcard': 'text/vcard',
  'vcf': 'text/x-vcard',
  'vcs': 'text/x-vcalendar',
  'wml': 'text/vnd.wap.wml',
  'wmls': 'text/vnd.wap.wmlscript',
  // val.contains('xml') from 'package:mime/src/default_extension_map.dart';
  'atom': 'application/atom+xml',
  'atomcat': 'application/atomcat+xml',
  'atomsvc': 'application/atomsvc+xml',
  'bdm': 'application/vnd.syncml.dm+wbxml',
  'ccxml': 'application/ccxml+xml',
  'cdxml': 'application/vnd.chemdraw+xml',
  'dae': 'model/vnd.collada+xml',
  'davmount': 'application/davmount+xml',
  'dbk': 'application/docbook+xml',
  'dd2': 'application/vnd.oma.dd2+xml',
  'docx':
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'dotx':
      'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
  'dtb': 'application/x-dtbook+xml',
  'dtd': 'application/xml-dtd',
  'emma': 'application/emma+xml',
  'es3': 'application/vnd.eszigno3+xml',
  'et3': 'application/vnd.eszigno3+xml',
  'gml': 'application/gml+xml',
  'gpx': 'application/gpx+xml',
  'gramps': 'application/x-gramps-xml',
  'grxml': 'application/srgs+xml',
  'hal': 'application/vnd.hal+xml',
  'ink': 'application/inkml+xml',
  'inkml': 'application/inkml+xml',
  'irp': 'application/vnd.irepository.package+xml',
  'kml': 'application/vnd.google-earth.kml+xml',
  'lasxml': 'application/vnd.las.las+xml',
  'lbe': 'application/vnd.llamagraphics.life-balance.exchange+xml',
  'link66': 'application/vnd.route66.link66+xml',
  'lostxml': 'application/lost+xml',
  'mads': 'application/mads+xml',
  'mathml': 'application/mathml+xml',
  'meta4': 'application/metalink4+xml',
  'metalink': 'application/metalink+xml',
  'mets': 'application/mets+xml',
  'mods': 'application/mods+xml',
  'mpkg': 'application/vnd.apple.installer+xml',
  'mrcx': 'application/marcxml+xml',
  'mscml': 'application/mediaservercontrol+xml',
  'musicxml': 'application/vnd.recordare.musicxml+xml',
  'mxl': 'application/vnd.recordare.musicxml',
  'mxml': 'application/xv+xml',
  'ncx': 'application/x-dtbncx+xml',
  'omdoc': 'application/omdoc+xml',
  'opf': 'application/oebps-package+xml',
  'osfpvg': 'application/vnd.yamaha.openscoreformat.osfpvg+xml',
  'pls': 'application/pls+xml',
  'potx':
      'application/vnd.openxmlformats-officedocument.presentationml.template',
  'ppsx':
      'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
  'pptx':
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'pskcxml': 'application/pskc+xml',
  'rdf': 'application/rdf+xml',
  'res': 'application/x-dtbresource+xml',
  'rif': 'application/reginfo+xml',
  'rl': 'application/resource-lists+xml',
  'rld': 'application/resource-lists-diff+xml',
  'rs': 'application/rls-services+xml',
  'rsd': 'application/rsd+xml',
  'rss': 'application/rss+xml',
  'sbml': 'application/sbml+xml',
  'sdkd': 'application/vnd.solent.sdkm+xml',
  'sdkm': 'application/vnd.solent.sdkm+xml',
  'shf': 'application/shf+xml',
  'sldx': 'application/vnd.openxmlformats-officedocument.presentationml.slide',
  'smi': 'application/smil+xml',
  'smil': 'application/smil+xml',
  'sru': 'application/sru+xml',
  'srx': 'application/sparql-results+xml',
  'ssdl': 'application/ssdl+xml',
  'ssml': 'application/ssml+xml',
  'stc': 'application/vnd.sun.xml.calc.template',
  'std': 'application/vnd.sun.xml.draw.template',
  'sti': 'application/vnd.sun.xml.impress.template',
  'stw': 'application/vnd.sun.xml.writer.template',
  'svg': 'image/svg+xml',
  'svgz': 'image/svg+xml',
  'sxc': 'application/vnd.sun.xml.calc',
  'sxd': 'application/vnd.sun.xml.draw',
  'sxg': 'application/vnd.sun.xml.writer.global',
  'sxi': 'application/vnd.sun.xml.impress',
  'sxm': 'application/vnd.sun.xml.math',
  'sxw': 'application/vnd.sun.xml.writer',
  'tei': 'application/tei+xml',
  'teicorpus': 'application/tei+xml',
  'tfi': 'application/thraud+xml',
  'uoml': 'application/vnd.uoml+xml',
  'uvt': 'application/vnd.dece.ttml+xml',
  'uvvt': 'application/vnd.dece.ttml+xml',
  'vxml': 'application/voicexml+xml',
  'wbs': 'application/vnd.criticaltools.wbs+xml',
  'wbxml': 'application/vnd.wap.wbxml',
  'wsdl': 'application/wsdl+xml',
  'wspolicy': 'application/wspolicy+xml',
  'x3d': 'model/x3d+xml',
  'x3dz': 'model/x3d+xml',
  'xaml': 'application/xaml+xml',
  'xdf': 'application/xcap-diff+xml',
  'xdm': 'application/vnd.syncml.dm+xml',
  'xdp': 'application/vnd.adobe.xdp+xml',
  'xdssc': 'application/dssc+xml',
  'xenc': 'application/xenc+xml',
  'xer': 'application/patch-ops-error+xml',
  'xht': 'application/xhtml+xml',
  'xhtml': 'application/xhtml+xml',
  'xhvml': 'application/xv+xml',
  'xlf': 'application/x-xliff+xml',
  'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'xltx':
      'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
  'xml': 'application/xml',
  'xop': 'application/xop+xml',
  'xpl': 'application/xproc+xml',
  'xsl': 'application/xml',
  'xslt': 'application/xslt+xml',
  'xsm': 'application/vnd.syncml+xml',
  'xspf': 'application/xspf+xml',
  'xul': 'application/vnd.mozilla.xul+xml',
  'xvm': 'application/xv+xml',
  'xvml': 'application/xv+xml',
  'yin': 'application/yin+xml',
  'zaz': 'application/vnd.zzazz.deck+xml',
  'zmm': 'application/vnd.handheld-entertainment+xml',
  // val.contains('json') from 'package:mime/src/default_extension_map.dart';
  'gltf': 'model/gltf+json',
  'json': 'application/json',
  'jsonml': 'application/jsonml+json',
  'webmanifest': 'application/manifest+json',

  // customize
  // 'yml': 'application/yaml',
  'yaml': 'application/yaml',
  'toml': 'application/toml',
};
